# version: '3.8' --> ini ga perlu lagi di docker versi terbaru

services:
  # Mesin 1: Web Server (Apache + PHP)
  web:
    build: . # Merujuk pada file Dockerfile
    ports:
    - "8080:80"
    volumes:
      # Expose htdocs ke host
      - ./htdocs:/var/www/html
    depends_on:
    - db

  # Mesin 2: Database Server (MySQL)
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: farrel
      MYSQL_DATABASE: hello_db
    ports:
    - "3307:3306"
    volumes:
     # Expose /var/lib/mysql ke host
    - ./mysql-data:/var/lib/mysql

  # Mesin 3: phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
    - "8081:80"
    environment:
      PMA_HOST: db
    depends_on:
    - db